<?php

namespace Database\Seeders;

use App\Models\Producto;
use App\Models\Categoria;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productos = [
            // BEBIDAS
            [
                'nombre' => 'Café Americano',
                'descripcion' => 'Café negro tradicional - GRATIS',
                'precio' => 0.00,
                'imagen' => '/logo.jpg',
                'categoria_id' => 1,
                'disponible' => true,
                'destacado' => true,
                'stock' => 100,
            ],
            [
                'nombre' => 'Café con Leche',
                'descripcion' => 'Café con leche cremosa',
                'precio' => 5.00,
                'imagen' => '/logo.jpg',
                'categoria_id' => 1,
                'disponible' => true,
                'destacado' => false,
                'stock' => 100,
            ],
            [
                'nombre' => 'Manzanilla',
                'descripcion' => 'Té de manzanilla relajante',
                'precio' => 3.00,
                'imagen' => '/logo.jpg',
                'categoria_id' => 1,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Té Puro',
                'descripcion' => 'Té negro tradicional',
                'precio' => 3.00,
                'imagen' => '/logo.jpg',
                'categoria_id' => 1,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Anís',
                'descripcion' => 'Té de anís digestivo',
                'precio' => 3.00,
                'imagen' => '/logo.jpg',
                'categoria_id' => 1,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Té Piteado con Pisco',
                'descripcion' => 'Deliciosa infusión con pisco peruano',
                'precio' => 15.00,
                'imagen' => '/logo.jpg',
                'categoria_id' => 1,
                'disponible' => true,
                'destacado' => true,
                'stock' => 30,
            ],
            
            // CREPES SALADOS
            [
                'nombre' => 'Crepe de Pollo',
                'descripcion' => 'Crepe simple con pollo deshilachado',
                'precio' => 8.00,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => true,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe de Queso',
                'descripcion' => 'Crepe simple con queso derretido',
                'precio' => 8.00,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe de Jamón',
                'descripcion' => 'Crepe simple con jamón',
                'precio' => 8.00,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe de Huevo',
                'descripcion' => 'Crepe simple con huevo',
                'precio' => 8.00,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Pollo y Queso',
                'descripcion' => 'Crepe doble: combina pollo y queso',
                'precio' => 11.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => true,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Queso y Jamón',
                'descripcion' => 'Crepe doble: combina queso y jamón',
                'precio' => 11.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Jamón y Pollo',
                'descripcion' => 'Crepe doble: combina jamón y pollo',
                'precio' => 11.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Huevo y Pollo',
                'descripcion' => 'Crepe doble: combina huevo y pollo',
                'precio' => 11.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Queso y Huevo',
                'descripcion' => 'Crepe doble: combina queso y huevo',
                'precio' => 11.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Pollo, Queso y Huevo',
                'descripcion' => 'Crepe triple: combina pollo, queso y huevo',
                'precio' => 13.00,
                'imagen' => '/crepeChocolate_Fresa_y_Durazo.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => true,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Queso, Jamón y Huevo',
                'descripcion' => 'Crepe triple: combina queso, jamón y huevo',
                'precio' => 13.00,
                'imagen' => '/crepeChocolate_Fresa_y_Durazo.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            [
                'nombre' => 'Crepe Jamón, Pollo y Queso',
                'descripcion' => 'Crepe triple: combina jamón, pollo y queso',
                'precio' => 13.00,
                'imagen' => '/crepeChocolate_Fresa_y_Durazo.jpg',
                'categoria_id' => 2,
                'disponible' => true,
                'destacado' => false,
                'stock' => 50,
            ],
            
            // CREPES DULCES
            [
                'nombre' => 'Mermelada de Fresa',
                'descripcion' => 'Crepe con mermelada de fresa casera',
                'precio' => 7.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => true,
                'stock' => 40,
            ],
            [
                'nombre' => 'Mermelada de Aguaymanto',
                'descripcion' => 'Crepe con mermelada de aguaymanto',
                'precio' => 7.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => false,
                'stock' => 40,
            ],
            [
                'nombre' => 'Mermelada de Sauco',
                'descripcion' => 'Crepe con mermelada de sauco',
                'precio' => 7.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => false,
                'stock' => 40,
            ],
            [
                'nombre' => 'Mermelada de Piña',
                'descripcion' => 'Crepe con mermelada de piña',
                'precio' => 7.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => false,
                'stock' => 40,
            ],
            [
                'nombre' => 'Mermelada de Naranja',
                'descripcion' => 'Crepe con mermelada de naranja',
                'precio' => 7.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => false,
                'stock' => 40,
            ],
            [
                'nombre' => 'Manjar Blanco',
                'descripcion' => 'Crepe con manjar blanco (dulce de leche)',
                'precio' => 6.50,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => true,
                'stock' => 40,
            ],
            [
                'nombre' => 'Nutella',
                'descripcion' => 'Crepe con Nutella y frutas',
                'precio' => 12.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => true,
                'stock' => 40,
            ],
            [
                'nombre' => 'Leche Condensada',
                'descripcion' => 'Crepe con leche condensada',
                'precio' => 7.50,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => false,
                'stock' => 40,
            ],
            [
                'nombre' => 'Chocolate',
                'descripcion' => 'Crepe con chocolate derretido',
                'precio' => 7.50,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 3,
                'disponible' => true,
                'destacado' => true,
                'stock' => 40,
            ],
            
            // ESPECIALES DE LA CASA
            [
                'nombre' => 'Banana Split',
                'descripcion' => 'Bananas con chocolate y crema chantilly',
                'precio' => 12.00,
                'imagen' => '/crepeChocolate_Fresa_y_Durazo.jpg',
                'categoria_id' => 4,
                'disponible' => true,
                'destacado' => true,
                'stock' => 20,
            ],
            [
                'nombre' => 'Crocante',
                'descripcion' => 'Chocolate con deliciosas pecanas y ron',
                'precio' => 12.00,
                'imagen' => '/crepeChocolate_Fresa_y_Durazo.jpg',
                'categoria_id' => 4,
                'disponible' => true,
                'destacado' => false,
                'stock' => 20,
            ],
            [
                'nombre' => 'Sol y Sombra',
                'descripcion' => 'Chocolate con coco rallado',
                'precio' => 9.00,
                'imagen' => '/crepeChocolate.jpg',
                'categoria_id' => 4,
                'disponible' => true,
                'destacado' => false,
                'stock' => 20,
            ],
            [
                'nombre' => 'Tres Quesos',
                'descripcion' => 'Cheddar, paria y mozzarella',
                'precio' => 11.00,
                'imagen' => '/crepeChocolateFresa.jpg',
                'categoria_id' => 4,
                'disponible' => true,
                'destacado' => true,
                'stock' => 20,
            ],
        ];

        foreach ($productos as $producto) {
            Producto::create($producto);
        }
    }
}
